### ISSUE TITLE
I cannot see any of the applications for my grants:

### ISSUE THREAD

**Issue by YorgunKelebek** [goofballLogic/g4a-spa#12]
> I cannot see any of the applications for my grants:
> 
> ![image](https://user-images.githubusercontent.com/56796626/120114563-97fad800-c177-11eb-8999-c23082ea7c9e.png)
> 
> Although I know there are some:
> 
> ![image](https://user-images.githubusercontent.com/56796626/120114586-ad700200-c177-11eb-9f66-f890a07e7139.png)

Can you check whether this was a caching issue?

_Originally posted by @goofballLogic in https://github.com/goofballLogic/g4a-spa/issues/7#issuecomment-851051303_

**Comment by YorgunKelebek** [comment]
I think this could be because these applications were made before the workflow addition...?

**Comment by goofballLogic** [comment]
Yes I've checked and the data was stored incorrectly because this application was created using an older version of the software. I've corrected it and put it back in "Draft" mode so you should be able to see it again now.

**Comment by YorgunKelebek** [comment]
Sorry, still can't see it on the portal as an applicant

![image](https://user-images.githubusercontent.com/56796626/120207154-fc737100-c223-11eb-9d2b-689f3957ac9d.png)

**Comment by goofballLogic** [comment]
ok I revisited the security stuff. There'll likely be some new issues introduced by this change, but hopefully this one is fixed.

**Comment by YorgunKelebek** [comment]
Tested OK
